### PR TITLE
perf(lab): noise-resistant gate (best-of-N), readable summary chart, fail-loud compiles, and baseline refresh for the unified execute API

### PR DESCRIPTION
**Pull request by David-Engel**
## Description

Hardens the perf-lab regression gate and its reporting, and refreshes the harness for the unified execute API landed in #143.

The original scope was noise resistance: a benchmark that tripped the threshold was re-measured **once** and kept as a regression if it tripped again, which still fails on a transient outlier when the noisy window spans both the initial run and the immediate re-run (a `primitives/decode` +26% false alarm that does not reproduce). That work is here, plus the follow-ons that came out of running it in the lab: a readable summary chart, chart/gate reconciliation, a fail-loud compile step, the summary echoed to the log, verification of implausibly large *improvements*, and the baseline/API refresh those runs exposed.

## Changes

**1. Best-of-N auto-confirm (noise resistance)**

A tripped benchmark is now re-measured **`BENCH_CONFIRM_RUNS` times** (default 4; interleaved, offenders only) and counted as a real regression only if it trips in a **majority** of those re-runs (`BENCH_CONFIRM_QUORUM`, default `N/2+1` = 3 of 4). A true regression reproduces consistently; noise does not. Both knobs are env-overridable. The gate threshold itself is unchanged (`BENCH_REGRESSION_RATIO`, default 1.10).

**2. Diverging-bar summary chart**

`summary.md` now leads with a colored bar table (🟩 faster / 🟥 slower, one square ≈ 1%, drawn only for |Δ| ≥ 1%) so a run's shape is readable at a glance instead of requiring a scan of the raw `critcmp` output. The raw table is retained below it, relabeled "Raw first-pass measurements".

**3. Chart/gate reconciliation**

The chart previously showed the *first-pass* number for a benchmark that was re-measured, so a benchmark cleared as noise could still render as a red bar — the summary appeared to contradict the verdict. Re-measured rows now display the **median** of `{first pass + all re-runs}` and are marked `⟳`. Median rather than "first passing result" so the displayed number is not cherry-picked.

**4. Bench compile failures are surfaced (fail loud)**

The bench binaries were compiled inside the JSON-enumeration step (`cargo bench --no-run --message-format=json 2>/dev/null | ...`), which discards cargo's stderr and swallows the JSON error records, so a compilation failure aborted the run with no diagnostics in the log — it surfaced only as a generic "no bench binaries found". Both runners now run an explicit `cargo bench --no-run` for candidate and baseline with human-readable output that fails loudly (sh: check cargo's exit status; ps1: `Invoke-Native` throws). The subsequent JSON enumeration just reads the already-built, cached binaries.

**5. Baseline advanced to `bb02ba65`, harness updated for the new API**

The harness compiles one bench source against **both** the candidate and baseline `mssql-tds`, so a breaking library change forces the baseline forward. #143 (unified execute + statement-wise result navigation) is such a change: the current benches no longer compile against the prior baseline (`6f8db4a0`). `baseline-commit.txt` now points at `bb02ba65` — the commit that introduced the API, i.e. the *earliest* library that compiles the current benches, which preserves the longest comparison window.

Advancing the baseline then exposed a runtime break in the harness. #143 funnels the `sp_prepexec` `@handle` (RETURNVALUE ordinal 0) into a dedicated slot read via `take_prepared_statement_handle()` instead of leaving it in the generic return-values buffer, but `drain_capture_handle()` still scanned `get_return_values()` for the first integer and panicked (`prepared handle not found in return values`). It compiled fine — only the runtime data moved. It now reads the new getter.

**6. `summary.md` is echoed to the log**

The summary reached only the run's **Summary** tab via `task.uploadsummary`, so the verdict and comparison were invisible when triaging from the log. It is now also echoed into the log, before the pass/fail branch so it appears on failing runs too.

**7. Large improvements are verified too**

The gate is one-directional, so a *baseline*-slower result was never challenged and an implausible win was published unverified. The Windows run showed exactly that: `select_n_rows/1000` and `/10000` reported the baseline **3.0× and 3.35× slower** with tight CIs — but Linux on the same commits showed 1.00×, no commit between the baseline and main touches the row-fetch path, and the anomaly was confined to two *consecutive* benchmarks in the middle of one pass with normal neighbours on either side. That is a sustained host disturbance, not a real gain.

Benchmarks where the baseline is slower by ≥ `BENCH_IMPROVEMENT_VERIFY_RATIO` — defaulting to **the same threshold as regressions** (`BENCH_REGRESSION_RATIO`, 1.10) — now join the same re-measure set as gate offenders, so the re-runs still cost one pass. Both directions are verified at the same magnitude deliberately: these measurements are headed for a database for run-over-run trend comparison, where a baseline pass slowed by transient noise corrupts the record exactly as much as a slowed candidate pass. The summary reports whether the win reproduced in a majority of re-runs, and the chart applies the same median reconciliation, so an unreproduced 3× no longer renders as a full-width green bar. This never fails the run — it keeps the recorded numbers honest, and a win that *does* reproduce is worth a look too, since it can mean the candidate is doing less work rather than the same work faster.

**8. Documentation**

`docs/perf-testing-plan.md` now covers the summary chart, the median reconciliation, the fail-loud compile step, and improvement verification, and records **why a breaking `mssql-tds` API change forces the baseline forward** — one bench source must compile against both libraries — including which commit to advance to and why the alternatives (`cfg`-gating; per-side bench sources) are worse.

**Files**

- `mssql-tds-bench/perf-lab/run-benchmarks.sh` — best-of-N tally/quorum, improvement verification, emoji bar table with median overrides, explicit compile step, summary echo.
- `mssql-tds-bench/perf-lab/run-benchmarks.ps1` — mirror of the above (hashtable tally, `Get-EmojiBarTable`, `Invoke-CompileBenches`).
- `mssql-tds-bench/perf-lab/baseline-commit.txt` — `6f8db4a0` → `bb02ba65`.
- `mssql-tds-bench/src/lib.rs` — `drain_capture_handle()` reads `take_prepared_statement_handle()`; drop the now-unused `ColumnValues` import.
- `docs/perf-testing-plan.md` — best-of-N auto-confirm, reporting behavior, and the baseline/API coupling.

## Validation

- **Linux lab run [164601](https://sqlclientdrivers.visualstudio.com/mssql-rs/_build/results?buildId=164601) passed** end-to-end on the final commit (rebased on latest `main`, both sides compiling, no panic). A Windows run is in flight.
- **Best-of-N proven in the lab**: run 163041 had `strings` trip +11% on the first pass; it was re-measured 4×, tripped 0/4, and was correctly cleared as transient — the run passed instead of failing on noise.
- **Compile-failure surfacing proven by a real failure**: after rebasing onto `main` with the #143 API break deliberately unfixed, the run failed with the cargo errors printed in the log and a clear `bench compilation failed` message, rather than the old silent "no bench binaries found".
- **Baseline bump verified** by swapping in `mssql-tds@bb02ba65` and compiling all seven bench binaries — the exact operation the harness performs.
- **`sp_prepexec` fix verified** against a local SQL 2022: `prepared_prepexec` completed 1320 iterations (prepexec + unprepare per iteration) with no panic.
- **Improvement verification checked against the real Windows table**: both runners select exactly the two anomalous benchmarks and no false regressions, and with non-reproducing re-runs the median collapses them from −66%/−70% to −1.0%/+1.0% marked `⟳` instead of rendering as full-width green bars. A synthetic 1.15× baseline-slower row confirms the 1.10 default widens the net as intended while 1.04 is ignored. sh and PowerShell produce identical selections and medians.
- Reproduced the original `primitives/decode` alarm locally (candidate = `main`, baseline = `6f8db4a0`, harness held constant): across five A/B passes the delta swung +31/+20/+15/±2/−8% with the slower side flipping randomly — pure host noise, so under the 3-of-4 rule it would not fail the gate. No change in `6f8db4a0..main` touches the row-decode hot path.
- `bash -n` and PowerShell AST parse clean; quorum logic checked (2/4 not confirmed at the default quorum of 3, 3/4 confirmed); sh and ps1 chart/median paths produce identical output for the same inputs.

## Related Issues

[AB#46061](https://sqlclientdrivers.visualstudio.com/b95cf060-8083-439d-8ef1-405d5bf219d8/_workitems/edit/46061)

## Checklist

- [x] New/changed functionality has tests — N/A: perf-lab runner logic and bench harness (no product code); validated via the lab runs, `bash -n`, PowerShell parse, and the local checks above
- [x] Public API changes are documented — N/A: no public API changes

### CODE REVIEW

File: mssql-tds-bench/perf-lab/run-benchmarks.sh [hunk 1]
```diff
@@ -303,90 +317,217 @@ regression_ids() {
...
+# CPU-bound benches (e.g. the decode microbenches) can swing double digits on a
+# shared VM. So re-measure ONLY the benchmarks that tripped — interleaved per
+# binary, same as the main run — several times, and keep as a real regression
+# only those that trip in a MAJORITY of the re-runs. A true regression reproduces
+# consistently; noise does not. Both bench binaries are already built and the
+# offenders are a small subset, so the extra re-runs stay cheap.
+#   BENCH_CONFIRM_RUNS   (default 4)              — number of re-runs
+#   BENCH_CONFIRM_QUORUM (default majority = N/2+1) — re-runs required to confirm
+CONFIRM_RUNS="${BENCH_CONFIRM_RUNS:-4}"
+QUORUM="${BENCH_CONFIRM_QUORUM:-$(( CONFIRM_RUNS / 2 + 1 ))}"
```
[the remark this answers is not in the document]
Comment (David-Engel) [reply mssql-tds-bench/perf-lab/run-benchmarks.sh:393]: Good catch — fixed in 6dd609b6. Both knobs are now range-checked before use: `BENCH_CONFIRM_RUNS` must be a positive integer `>= 1`, and `BENCH_CONFIRM_QUORUM` must satisfy `1 <= QUORUM <= CONFIRM_RUNS`; anything else exits 1 with an explicit message rather than silently weakening the gate. `CONFIRM_RUNS` is validated *before* `QUORUM` is derived, since that default is an arithmetic expansion that would otherwise fail with a confusing `unbound variable` error on a non-numeric value. Verified that `RUNS=0`, `RUNS=-1`, `RUNS=abc`, `QUORUM=0` and `QUORUM=5 of 4` are all rejected, while defaults and `RUNS=6 QUORUM=4` are accepted.

File: mssql-tds-bench/perf-lab/run-benchmarks.ps1 [hunk 2]
```diff
@@ -429,93 +448,215 @@ $thr = [double]($env:BENCH_REGRESSION_RATIO)
...
+# CPU-bound benches (e.g. the decode microbenches) can swing double digits on a
+# shared VM. So re-measure ONLY the benchmarks that tripped - interleaved per
+# binary, same as the main run - several times, and keep as a real regression
+# only those that trip in a MAJORITY of the re-runs. A true regression reproduces
+# consistently; noise does not. Both bench binaries are already built and the
+# offenders are a small subset, so the extra re-runs stay cheap.
+#   BENCH_CONFIRM_RUNS   (default 4)                - number of re-runs
+#   BENCH_CONFIRM_QUORUM (default majority = N/2+1)  - re-runs required to confirm
+$confirmRuns = if ($env:BENCH_CONFIRM_RUNS) { [int]$env:BENCH_CONFIRM_RUNS } else { 4 }
+$quorum = if ($env:BENCH_CONFIRM_QUORUM) { [int]$env:BENCH_CONFIRM_QUORUM } else { [int][math]::Floor($confirmRuns / 2) + 1 }
```
[the remark this answers is not in the document]
Comment (David-Engel) [reply mssql-tds-bench/perf-lab/run-benchmarks.ps1:491]: Fixed in 6dd609b6, mirroring the sh runner: `if ($confirmRuns -lt 1) { throw ... }` and `if ($quorum -lt 1 -or $quorum -gt $confirmRuns) { throw ... }`, so a gate-disabling configuration aborts the run instead of quietly clearing every regression. (A non-numeric value already hard-fails on the `[int]` cast with a clear message.) Verified the same matrix of configurations as the sh side.

File: mssql-tds-bench/perf-lab/run-benchmarks.sh [hunk 3]
```diff
@@ -303,90 +317,217 @@ regression_ids() {
...
+# spike. Only offenders are re-measured, so only they are reconciled; the raw
+# critcmp block in the summary keeps the untouched first-pass data.
+MEDIANS_FILE="$RESULTS_DIR/offender-medians.txt"
+: > "$MEDIANS_FILE"
+for id in $OFFENDERS; do
+    med=$(
+        {
+            ratio_in_file "$id" "$RESULTS_DIR/comparison.txt"
+            for run in $(seq 1 "$CONFIRM_RUNS"); do ratio_in_file "$id" "$RESULTS_DIR/confirm-run${run}.txt"; done
+        } | grep -E '^[0-9.]+$' | median_stdin
```
[the remark this answers is not in the document]
Comment (David-Engel) [reply mssql-tds-bench/perf-lab/run-benchmarks.sh]: Agreed — this is a real selection-bias bug, fixed in 6dd609b6. The median is now taken over the **re-runs only**, the same measurements the quorum counts; the first pass is excluded because a benchmark is re-measured precisely *because* that pass was extreme, so including it re-counts the outlier under test.

Reproduced your scenario numerically (first pass +15%, 2 of 4 re-runs tripping, so the gate clears it):
- old rule, median of {first pass + 4 re-runs} = 1.1200 → chart **+12.0%**, at/above the 10% threshold while the verdict passes — exactly the contradiction you describe;
- new rule, median of the 4 re-runs = 1.0750 → chart **+7.5%**, below threshold and consistent with the passing verdict.

File: mssql-tds-bench/perf-lab/run-benchmarks.ps1 [hunk 4]
```diff
@@ -429,93 +448,215 @@ $thr = [double]($env:BENCH_REGRESSION_RATIO)
...
+    if ($n % 2) { return $s[[int](($n - 1) / 2)] } else { return ($s[[int]($n / 2 - 1)] + $s[[int]($n / 2)]) / 2 }
+}
+$overrides = @{}
+foreach ($o in $regressions) {
+    $vals = @()
+    $mr = Get-RatioFor $comparison $o.Name
+    if ($null -ne $mr) { $vals += $mr }
+    foreach ($cc in $confirmRunComparisons) {
+        $rr = Get-RatioFor $cc $o.Name
+        if ($null -ne $rr) { $vals += $rr }
```
[the remark this answers is not in the document]
Comment (David-Engel) [reply mssql-tds-bench/perf-lab/run-benchmarks.ps1]: Same fix as the sh thread, applied in 6dd609b6: `$overrides` is now built from `$confirmRunComparisons` only, dropping the `Get-RatioFor $comparison` first-pass sample, so the displayed value comes from the same measurements `$tally`/`$confirmed` are derived from. Verified sh and PowerShell produce identical medians on the same inputs.

File: mssql-tds-bench/perf-lab/run-benchmarks.sh [hunk 5]
```diff
@@ -258,6 +271,7 @@ echo ">>> Adding baseline worktree for ${BASELINE_COMMIT} at ${BASELINE_TREE}...
 git worktree add --detach "$BASELINE_TREE" "$BASELINE_COMMIT"
 echo ">>> Building baseline bench binaries (target-base/)..."
 swap_to_baseline
+compile_benches "$REPO_ROOT/target-base" "baseline"
 BASE_BINS="$(bench_bins "$REPO_ROOT/target-base")"
 restore_candidate
 git worktree remove --force "$BASELINE_TREE" || true
```
[the remark this answers is not in the document]
Comment (David-Engel) [reply mssql-tds-bench/perf-lab/run-benchmarks.sh:289]: Correct, and this one bit me manually earlier in development — fixed in 6dd609b6. An `EXIT` trap is now installed immediately after `swap_to_baseline` and cleared only after `restore_candidate` and the worktree removal succeed, so any exit in between (a baseline compile failure, or `set -e` on anything else) still restores the tree.

Verified with a simulated baseline compile failure in a scratch repo: exit code 1 with the cargo errors still visible, `mssql-tds/` back to the candidate source, no stray `.mssql-tds-candidate`, and the worktree unregistered.

File: mssql-tds-bench/perf-lab/run-benchmarks.ps1 [hunk 6]
```diff
@@ -385,13 +402,15 @@ function Restore-CandidateSource {
...
 Write-Host '>>> Building candidate bench binaries (target/)...'
+Invoke-CompileBenches (Join-Path $RepoRoot 'target') 'candidate'
 $script:CandBins = Get-BenchBinaries (Join-Path $RepoRoot 'target')
 if ($script:CandBins.Count -eq 0) { throw 'no candidate bench binaries found' }
 
 Write-Host ">>> Adding baseline worktree for $BaselineCommit at $BaselineTree..."
 Invoke-Native { git worktree add --detach $BaselineTree $BaselineCommit }
 Write-Host '>>> Building baseline bench binaries (target-base/)...'
 Set-BaselineSource
+Invoke-CompileBenches (Join-Path $RepoRoot 'target-base') 'baseline'
```
[the remark this answers is not in the document]
Comment (David-Engel) [reply mssql-tds-bench/perf-lab/run-benchmarks.ps1]: Fixed in 6dd609b6: the swapped-source build and enumeration are wrapped in `try`, with `Restore-CandidateSource` and the worktree removal in `finally`, so a compile failure cannot leave the checkout on baseline source or the worktree registered. The `finally` uses a non-throwing worktree removal so it cannot mask the original compile error.

File: mssql-tds-bench/perf-lab/run-benchmarks.sh [hunk 7]
```diff
@@ -295,98 +322,318 @@ cpu_sample "interleave-end" || true
...
+    awk -v thr="$IMP_THR" '
+        $2 ~ /^[0-9]+\.[0-9]+$/ && $6 ~ /^[0-9]+\.[0-9]+$/ && ($2 + 0) >= thr { print $1, $2 }
+    ' "$1"
+}
+
+IMPROVEMENTS=$(improvement_ids "$RESULTS_DIR/comparison.txt")
+# One re-measure set covers both directions, so the re-runs cost one pass.
+# awk 'NF' drops the blank lines rather than grep, which would exit 1 when both
+# lists are empty (a clean run) and kill the script under set -e.
+VERIFY_IDS=$(printf '%s\n%s\n' "$OFFENDERS" "$IMPROVEMENTS" | awk 'NF' | sort -u)
```
Comment (saurabh500) [inline mssql-tds-bench/perf-lab/run-benchmarks.sh:369]: Out of scope for this PR — suggesting as a follow-up, not a blocker.

The improvement-verify set is unbounded: `IMPROVEMENTS` picks up *every* benchmark where the baseline is ≥10% slower, and they all join `VERIFY_IDS`, which drives `CONFIRM_RUNS` (default 4) release-grade re-runs each. On a noise-resistance PR like this one that's 0–2 benchmarks, so it's genuinely free as intended.

The cost only shows up on a *future* PR that legitimately optimizes a hot path — a dozen benchmarks could come in >10% faster and each would then be re-measured 4× at `BENCH_SECS=30`/`BENCH_SAMPLES=30`, adding several minutes. Regressions are self-limiting (a healthy PR has none); improvements are not.

Nothing to change here — it can't affect this PR's own runs, it never fails the gate, and it's already reactively mitigable via `BENCH_IMPROVEMENT_VERIFY_RATIO`. Worth a follow-up to cap the improvement set (e.g. top-K by magnitude) or default improvement verification to a higher ratio than regressions. The same applies to the PowerShell mirror (`Get-CritcmpImprovements` + `$verifyNames`).

File: docs/perf-testing-plan.md [hunk 8]
```diff
@@ -263,11 +301,25 @@ binaries keep the per-binary interleaving effective (see §2).
...
+  compile against both revisions, so once they are updated for a new API they no longer
+  build against a baseline that predates it, and the baseline compile fails. Advance
+  `baseline-commit.txt` to the commit that **introduced** the API — the earliest library
+  that compiles the current benches — which preserves the longest comparison window.
+  (`cfg`-gating the changed call sites so one source compiles both ways is possible but
+  costs dual code paths; reserve it for when a pre-break baseline is specifically needed.
+  Building each side from its own bench source is *not* an option: it reintroduces the
+  variable the harness exists to eliminate.) Bumping the baseline can also surface
+  *runtime* breaks that still compile — e.g. a value that moved from the generic
+  return-value buffer to a dedicated accessor.
```
Comment (saurabh500) [inline docs/perf-testing-plan.md:316]: 🔵 Nit (prose) — "a value that moved from the generic return-value buffer to a dedicated accessor" reads as if this PR (or the API break it tracks) *introduced* the accessor. The `prepared_statement_handle` slot + `take_prepared_statement_handle()` getter already existed on `main`; what actually changed is that the sp_prepexec `@handle` stopped landing in the generic `return_values` buffer, so the bench's old `get_return_values()` scan came up empty and its `.expect(...)` panicked. The accessor is the *fix*, not the thing that moved. Suggest wording like: "…a value that stopped being pushed to the generic return-value buffer, so the bench must now read it via its dedicated accessor." Purely descriptive; no code impact.

File: mssql-tds-bench/perf-lab/run-benchmarks.ps1 [hunk 9]
```diff
@@ -428,94 +466,276 @@ Write-Host $comparison
...
+    foreach ($cc in $confirmRunComparisons) {
+        $rr = Get-RatioFor $cc $name
+        if ($null -ne $rr) { $vals += $rr }
+    }
+    if ($vals.Count -gt 0) { $overrides[$name] = Get-Median $vals }
+}
+
+# --- Verdict (based on the majority-confirmed regressions) ---
 $pct = [int][math]::Round(($thr - 1) * 100)
+$impPct = [int][math]::Round(($impThr - 1) * 100)
```
Comment (saurabh500) [inline mssql-tds-bench/perf-lab/run-benchmarks.ps1:574]: 🔵 Nit (parity) — the two runners round percentages differently. Bash uses half-up (`printf "%d", x+0.5`), PowerShell uses banker's rounding here (`[math]::Round` defaults to `MidpointRounding.ToEven`). They only diverge at an exact `.5%` display boundary — e.g. a `2.5%` delta prints `3%` on Linux and `2%` on Windows. Selections, quorum, and medians are all identical; this is purely the rendered number in the summary. If you want byte-identical summaries across OSes, use `[math]::Round($x, [MidpointRounding]::AwayFromZero)` at the display sites. Author's discretion.

**Comment by saurabh500** [comment]
## Review verdict: ✅ Approve

The regression gate goes from "one noisy run can fail the build" to a best-of-N quorum that only trips when an offender reproduces in a majority of `CONFIRM_RUNS` re-measurements — a real, well-reasoned robustness win. I walked all five files; no blocking items.

**Correctness spot-checks that passed**
- Best-of-N: offenders re-measured `CONFIRM_RUNS`× (default 4), confirmed only on `QUORUM` (N/2+1). PS quorum's `[math]::Floor($confirmRuns/2)+1` correctly forces the int the `4/2`→`2.0` float would otherwise break.
- Median reconciliation: re-measured benches display the **median** of re-runs (marked ⟳) and deliberately exclude the first pass, so the outlier-under-test gets no tie-breaking vote.
- `lib.rs` fix is necessary, not cosmetic: `push_return_value` now diverts the sp_prepexec `@handle` before it reaches `return_values`, so the old `get_return_values()` scan would panic on `.expect(...)`; reading `take_prepared_statement_handle()` is the right repair. Compiled fine, would have broken at runtime — good catch.
- Baseline bump to `bb02ba65` is structurally the earliest mainline commit that compiles the current benches (single-parent, ancestor of `main`, after the unified-execute API landed).
- Both runners: `bash -n` clean, PS AST parse clean, `cargo clippy -p mssql-tds-bench --all-targets` clean.

**Non-blocking, tracked in inline threads**
- 🟣 Follow-up: unbounded improvement-verify set (top comment on `run-benchmarks.sh`).
- 🔵 Cross-OS rounding parity nit (`run-benchmarks.ps1`).
- 🔵 Doc prose imprecision on the accessor (`docs/perf-testing-plan.md`).

**What went well** — the median-reconciliation design shows careful thought: excluding the first pass from the re-run median is exactly right and easy to get wrong. The quorum math is correct in both a `$(( ))` integer shell and a float-division PowerShell, which is a subtle parity trap dodged deliberately. And the change stayed tightly scoped to the perf harness instead of sprawling into the product code the one runtime break touched. Nice work.

**Review by saurabh500 — APPROVED** [review]

File: mssql-tds-bench/perf-lab/run-benchmarks.sh (hunk 7 above)
Comment (David-Engel) [reply mssql-tds-bench/perf-lab/run-benchmarks.sh:369]: Agreed on all counts, and thanks for working through the cost model — the asymmetry you point out is the key insight: regressions are self-limiting because a healthy PR has none, while improvements are not, so an unbounded improvement set is a latent cost that only lands on the PR that most deserves a fast signal.

Taking this as a follow-up rather than expanding this PR. I will cap the improvement-verify set by magnitude (top-K, K env-overridable) so the re-run budget is bounded regardless of how many benchmarks come in faster, and mirror it in `Get-CritcmpImprovements` / `$verifyNames` on the PowerShell side. Tracking it with the other two nits in a follow-up PR.

File: docs/perf-testing-plan.md (hunk 8 above)
Comment (David-Engel) [reply docs/perf-testing-plan.md:316]: Good catch — you are right that the wording implies the accessor was introduced by the API break, when `prepared_statement_handle` and `take_prepared_statement_handle()` already existed on `main`. What actually changed is that the `sp_prepexec` `@handle` stopped being pushed into the generic `return_values` buffer, which is why the benchs `get_return_values()` scan came up empty and its `.expect(...)` panicked — the accessor is the fix, not the thing that moved.

Will take your suggested phrasing in the follow-up PR.

File: mssql-tds-bench/perf-lab/run-benchmarks.ps1 (hunk 9 above)
Comment (David-Engel) [reply mssql-tds-bench/perf-lab/run-benchmarks.ps1:574]: Nice catch — `[math]::Round` defaulting to `MidpointRounding.ToEven` against bashs half-up `printf "%d", x+0.5` is a real (if narrow) parity gap at exact `.5%` display boundaries. Agreed it is cosmetic only: selections, quorum, and medians are unaffected, so no run outcome changes.

I would rather have byte-identical summaries across OSes than not, so I will switch the display sites to `[math]::Round($x, [MidpointRounding]::AwayFromZero)` in the follow-up PR.
