### PR TITLE
Fix mssql-tds test compilation broken by semantic merge conflict on main

### LINKED ISSUE #355: main is red: mssql-tds lib test target fails to compile (E0061) after semantic merge conflict
### Describe the bug

`origin/main` (currently `c09c6711`) does not compile its test targets. Every PR that test-compiles `mssql-tds` fails, so validation is red across the board for the whole team.

The cause is a **semantic merge conflict** between two PRs that were each green in isolation:

| Commit | PR | Merged (UTC) | What it did |
|---|---|---|---|
| `6a122251` | #207 | Aug 21 01:52 | Added a new `#[cfg(test)]` helper `create_failing_capturing_client` that calls `TdsClient::new` with 4 arguments |
| `c09c6711` | #230 | Aug 21 16:42 | Changed `TdsClient::new` to take a 5th parameter `login_session_state_tokens: Vec<SessionStateToken>` and updated only the callsites present in its own tree |

Neither PR's validation ever saw the other's tree, so both passed and `main` broke at merge time. PR #230 correctly updated the near-identical twin helper `create_capturing_client` (~line 6049) but missed its sibling at ~line 6072.

Notably, **`cargo build` still succeeds** — the stale callsite lives inside a `#[cfg(test)]` module, so it is only compiled by test-compiling targets. That is why build-only CI legs are green while every test leg is red, which makes the breakage easy to misattribute to the PR under test rather than to `main`.

### Steps to reproduce

1. Check out `main` at `c09c6711`.
2. Run any target that compiles tests, e.g.:
   - `cargo bclippy` (`cargo clippy --workspace --frozen --all-features --all-targets -- -D warnings`; `--all-targets` includes tests), or
   - `cargo nextest run -p mssql-tds --lib`, or
   - `cargo btest`
3. Observe the compile error.

Note that `cargo build` at the same commit succeeds, which is the confusing part.

### Expected behavior

`main` compiles all targets, including test targets, so PR validation reflects the PR's own changes.

### Actual behavior

```
error[E0061]: this function takes 5 arguments but 4 arguments were supplied
    --> mssql-tds\src\connection\tds_client.rs:6072:22
     |
6072 |           let client = TdsClient::new(
     |  ______________________^^^^^^^^^^^^^^-
6073 | |             transport,
6074 | |             negotiated_settings,
6075 | |             execution_context,
6076 | |             client_context,
6077 | |         );
     | |_________- argument #5 of type `std::vec::Vec<token::tokens::SessionStateToken>` is missing
     |
note: associated function defined here
    --> mssql-tds\src\connection\tds_client.rs:379:19
     |
 379 |     pub(crate) fn new(
     |                   ^^^
...
 384 |         login_session_state_tokens: Vec<SessionStateToken>,
     |         --------------------------------------------------

For more information about this error, try `rustc --explain E0061`.
error: could not compile `mssql-tds` (lib test) due to 1 previous error
```

### Version

commit `c09c6711` (`mssql-tds` 0.1.0)

### Affected crate

mssql-tds

### Environment

- OS: Windows
- Reproduced with the repo's standard `cargo bclippy` alias

### Additional context

The fix is a one-line change: pass `Vec::new()` as the 5th argument in the `create_failing_capturing_client` test helper, matching the convention already used by the two working callsites at ~line 5904 and ~line 6049.

This is a CI-unblocking hotfix and should be reviewed and merged promptly.

### PR DESCRIPTION
**Pull request by saurabh500**
## Description

**`main` is currently red for every PR in the repo.** This is a one-line CI-unblocking hotfix; please review and merge promptly.

`origin/main` (`c09c6711`) does not compile its test targets, so any PR whose validation test-compiles `mssql-tds` fails regardless of that PR's own content.

### Root cause: semantic merge conflict

Two PRs that were each green in isolation:

| Commit | PR | Merged (UTC) | What it did |
|---|---|---|---|
| `6a122251` | #207 | Aug 21 01:52 | Added a new `#[cfg(test)]` helper `create_failing_capturing_client` that calls `TdsClient::new` with 4 arguments |
| `c09c6711` | #230 | Aug 21 16:42 | Changed `TdsClient::new` to take a 5th parameter `login_session_state_tokens: Vec<SessionStateToken>` and updated only the callsites present in its own tree |

Neither PR's validation ever saw the other's tree, so both passed and `main` broke at merge time. #230 correctly updated the near-identical twin helper `create_capturing_client` (~line 6049) but missed its sibling `create_failing_capturing_client` (~line 6072).

### Why `cargo build` passes but test targets fail

The stale callsite lives inside a `#[cfg(test)]` module, so it is only compiled by test-compiling targets. `cargo build` at `c09c6711` succeeds, while `cargo clippy --all-targets`, `cargo nextest`, and `cargo btest` all fail with:

```
error[E0061]: this function takes 5 arguments but 4 arguments were supplied
    --> mssql-tds\src\connection\tds_client.rs:6072:22
     | argument #5 of type `std::vec::Vec<token::tokens::SessionStateToken>` is missing
note: associated function defined here
    --> mssql-tds\src\connection\tds_client.rs:379:19
error: could not compile `mssql-tds` (lib test) due to 1 previous error
```

This is why build-only CI legs are green while every test leg is red — which makes the breakage easy to misattribute to the PR under test rather than to `main`.

### The change

Exactly one line added, matching the convention already used by the two working callsites at ~line 5904 and ~line 6049:

```diff
@@ -6074,6 +6074,7 @@ mod tests {
             negotiated_settings,
             execution_context,
             client_context,
+            Vec::new(),
         );
         (client, fail)
     }
```

No signature changes, no refactors, no drive-by cleanups.

## Related Issues

Fixes #355

## Validation

Reproduced the failure on the unfixed tree first, then verified the fix locally on Windows.

| Command | Result |
|---|---|
| `cargo bclippy` (before fix) | **FAIL** — reproduced `E0061` / `could not compile mssql-tds (lib test)` |
| `cargo bfmt` | **PASS** — exit 0, no formatting diff |
| `cargo bclippy` (after fix) | **PASS** — exit 0, zero warnings, `Finished dev profile in 43.38s` |
| `cargo nextest run -p mssql-tds --lib --frozen --no-fail-fast` | **PASS** — `Summary [27.593s] 1868 tests run: 1868 passed, 0 skipped`, exit 0 |

The lib test target compiles again and the full `mssql-tds` lib suite is green.

<details>
<summary>Note on the first test run</summary>

An initial run reported 7 failures in `connection::transport::certificate_validator::tests` and `connection::transport::win_tls::validate::tests`. Those were purely environmental: the TLS fixtures (`valid_cert.pem` / `valid_cert.der`) are generated by `mssql-tds/tests/test_certificates/generate_certs.sh` and are gitignored (`*.pem`), so they did not exist in this fresh worktree. The failures were `CertificateNotFound { path: "tests/test_certificates/valid_cert.pem" }` and `read der fixture: NotFound`. After running the generator, all 1868 tests pass. Unrelated to this change.

</details>

`Cargo.lock` is gitignored in this repo and is not part of this change.

## Checklist

- [x] `cargo bfmt` passes
- [x] `cargo bclippy` passes
- [ ] `cargo btest` passes — intentionally skipped; the full coverage sweep is unnecessary for a one-line test-helper fix. Targeted `cargo nextest run -p mssql-tds --lib` was run instead and is fully green (see above).
- [x] New/changed functionality has tests — n/a, this repairs an existing test helper
- [x] Public API changes are documented — n/a, no public API change

### CODE REVIEW

**Comment by saurabh500** [comment]
Closed as a duplicate — #354 by @David-Engel covers this and takes precedence.

That PR was opened first and its diff is byte-for-byte identical to this one (same blob hashes `c8ab8712..5f2e5887`, same single `Vec::new(),` line added to `create_failing_capturing_client`). It is already out of draft and linked to ADO work item 47254, so it is the one that should merge to unblock `main`.

Nothing unique here to salvage. Tracking issue #355 closed as a duplicate as well.
