### ISSUE TITLE
main is broken: `NetworkReader` impl in `test_client_support.rs` has stale `receive` method (E0407)

### ISSUE THREAD

**Issue by saurabh500** [microsoft/mssql-rs#228]
### Describe the bug

`main` does not compile test targets. Any command that builds test targets (`cargo nextest archive`, `cargo test --no-run`, `cargo clippy --all-targets`, `cargo btest`) fails with:

```
error[E0407]: method `receive` is not a member of trait `NetworkReader`
   --> mssql-tds/src/test_client_support.rs:410:9
    |
410 | /         async fn receive(&mut self, _buffer: &mut [u8]) -> TdsResult<usize> {
411 | |             Ok(0)
412 | |         }
    | |_________^ not a member of trait `NetworkReader`

error: could not compile `mssql-tds` (lib test) due to 1 previous error
```

Failing CI build: [166358](https://sqlclientdrivers.visualstudio.com/mssql-rs/_build/results?buildId=166358&view=results) (`GH-CI Build and Test`, `refs/heads/main` @ f6cdda7901da0a5bcf44ab50cb71dc92e0bade4a). Jobs `Build Linux` and `Build Linux ARM` both fail the `Build in Container` step with `Bash exited with code '101'`.

### Root cause — semantic merge conflict between #188 and #221

Neither PR is wrong on its own; they were validated against different bases and conflict only after both landed.

| Commit | PR | Change |
| --- | --- | --- |
| `5d11fa0d` | #188 | Added `ByteStreamTransport` to `test_client_support.rs`, including `impl NetworkReader { async fn receive(..) }` |
| `fc33c148` | #221 | Removed `receive` from the `NetworkReader` trait in `io/reader_writer.rs`, and removed the matching impl from `TokenReplayTransport` |

#221 branched before #188 landed, so it never saw the second `NetworkReader` impl and could not remove the now-orphaned `receive` from it. Git merged both cleanly (different regions of the file), producing a `main` that does not compile.

### Why only the Linux jobs failed

Not platform-specific. The offending code lives in `#[cfg(test)] pub(crate) mod byte_stream`, so it is only compiled when test targets are built. On a non-PR (CI) run of the `main` branch, the nextest archive step is the only step that builds test targets, and it is gated to Linux:

- `.pipeline/templates/build-template.yml` — the `Archive nextest results` step is wrapped in `${{ if eq(parameters.osType, 'Linux') }}` with `condition: ne(variables['Build.Reason'], 'PullRequest')`.
- `.pipeline/scripts/containerized-build.sh` — runs `cargo nextest archive` (the containerized Linux x64 / ARM jobs).
- Every other compile/lint/test step (`cargo build`, `bclippy.ps1`/`bclippy.sh`, `bfmt`, `cargo llvm-cov nextest`) is gated on `eq(variables['Build.Reason'], 'PullRequest')` and is therefore **skipped** on a `main` CI run.

So on `main`, Windows and macOS never compiled a test target and reported green. A PR build would have caught this on Windows (`bclippy.ps1` runs `--all-targets`) — the gap is that no PR was ever built against the merged state.

### Steps to reproduce

```bash
git checkout f6cdda7901da0a5bcf44ab50cb71dc92e0bade4a
cargo fetch
cd mssql-tds && cargo nextest archive --archive-file out.tar.zst
# or, equivalently:
cargo clippy --workspace --all-features --all-targets
```

### Expected behavior

`main` compiles test targets; `cargo bclippy` and `cargo btest` pass on every commit of `main`.

### Actual behavior

`mssql-tds` (lib test) fails to compile with E0407, exit code 101. Linux and Linux ARM build jobs fail on `main`.

### Version

mssql-tds 0.1.0 @ f6cdda7901da0a5bcf44ab50cb71dc92e0bade4a

### Affected crate

mssql-tds

### Environment

Reproduces on all platforms when test targets are built. Observed in CI on `ubuntu` x64 and arm64 containers with Rust 1.95.

### Additional context

Immediate fix: drop the orphaned `receive` from `impl NetworkReader for ByteStreamTransport` so it matches the `TokenReplayTransport` impl that #221 already updated.

Follow-up worth considering (not addressed by the fix PR): `main`-branch CI currently skips build, clippy, fmt, and test steps entirely because they are all gated on `Build.Reason == 'PullRequest'`. A `main` run that at minimum ran clippy `--all-targets` would catch this class of merge race on the first commit rather than leaving `main` red. Requiring PRs to be up to date with `main` before merge would prevent it outright.
