### ISSUE TITLE
main does not compile: util.rs references ERR_STRING_RIGHT_TRUNCATION after it was renamed to WARN_STRING_TRUNCATION

### ISSUE THREAD

**Issue by David-Engel** [microsoft/mssql-rs#411]
### Describe the bug

`main` is currently red at tip. `mssql-odbc` fails to compile with `E0432` because `mssql-odbc/src/api/util.rs` imports `ERR_STRING_RIGHT_TRUNCATION`, which no longer exists in `mssql-odbc/src/api/sqlstate.rs`.

This is a semantic merge conflict between two PRs that were each green on their own:

- #385 (`a5c4170c`) renamed `ERR_STRING_RIGHT_TRUNCATION` to `WARN_STRING_TRUNCATION` and updated every reference that existed at the time.
- #348 (`a4727140`, current tip of `main`) added `mssql-odbc/src/api/util.rs`, which references the **old** name. It branched before the rename, so its own CI run never saw the new name, and GitHub's merge produced no textual conflict.

Neither PR was ever built against the other's tip, so the break only materialized once both landed on `main`.

`util.rs` is compiled — `mssql-odbc/src/api/mod.rs:47` declares `pub(crate) mod util;` — so this is a hard build failure, not dead code.

### Steps to reproduce

```bash
git fetch origin
git checkout a4727140   # current tip of main
cargo check -p mssql-odbc --lib
```

### Expected behavior

`main` compiles cleanly.

### Actual behavior

```
error[E0432]: unresolved import `crate::api::sqlstate::ERR_STRING_RIGHT_TRUNCATION`
 --> mssql-odbc\src\api\util.rs:9:28
  |
9 | use crate::api::sqlstate::{ERR_STRING_RIGHT_TRUNCATION, post_diag};
  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ERR_STRING_RIGHT_TRUNCATION` in `api::sqlstate`
  |
help: a similar name exists in the module
  |
9 - use crate::api::sqlstate::{ERR_STRING_RIGHT_TRUNCATION, post_diag};
9 + use crate::api::sqlstate::{WARN_STRING_TRUNCATION, post_diag};
  |

error: could not compile `mssql-odbc` (lib) due to 1 previous error
```

Verified by checking out `a4727140` into a clean throwaway worktree and building it standalone, with no other branch involved.

### Version

commit `a4727140`

### Affected crate

mssql-odbc

### Environment

- OS: Windows
- Reproduces on any platform; this is a pure compile error with no runtime or SQL Server dependency.

### Additional context

**Suggested fix**

Point the two references in `mssql-odbc/src/api/util.rs` (lines 9 and 184) at `WARN_STRING_TRUNCATION`. Both constants carry the identical payload — `state: SQLSTATE_01004`, `text: "String data, right truncation"` — so this is a pure rename with no behavior change. The surrounding doc comment in `util.rs` already describes the intended behavior as "Truncation posts `01004` and returns `SQL_SUCCESS_WITH_INFO`", which matches `WARN_STRING_TRUNCATION` exactly.

**Note on PR #376**

PR #376 carries this same one-line fix, applied as part of resolving its merge with `main`, because the branch could not build at all otherwise. That fix is incidental to the PR's actual scope. Whichever of the two lands first, the other should drop or absorb the change on its next sync.

**Preventing a recurrence**

Per-PR CI cannot catch this class of failure: one PR renames a symbol, another adds a use of the old name, both are green individually, and `main` goes red only once both land. Neither branch is ever built against the other's tip.

Two standard guards would close the gap:

- Require branches to be up to date with `main` before merging (branch protection), so the second PR rebuilds against the first.
- Adopt a merge queue, which builds the combined result before it reaches `main`.

The merge-queue option is the stronger of the two and avoids the serialization cost of forcing every PR to re-sync.
